baseURL = "https://andrewjsut.github.io/"
languageCode = "en-us"
title = "Andrew Sutcliffe"
disableKinds = ["taxonomy", "term", "RSS"]
publishDir = "docs"


# For clean blog URLs:
[permalinks]
  blog = "/blog/:slug/"